name: push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Publish Nuget Panosen.Compling
      run: dotnet nuget push Panosen.Compling/bin/Release/Panosen.Compling.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Compling.LL1
      run: dotnet nuget push Panosen.Compling.LL1/bin/Release/Panosen.Compling.LL1.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Compling.SLR1
      run: dotnet nuget push Panosen.Compling.SLR1/bin/Release/Panosen.Compling.SLR1.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
